Fix the restconf deletion of leaf list items.
alliedtelesis/apteryx-xml pull request #100
Opened 2024-03-11 03:12 UTC by gcampbell512

Leaf list items were not being detected properly and hence not being set to NULL when the flag SCF_F_SET_NULL was set.

2024-03-11 03:38 UTC, tony-vanderpeet commented on schema.c
> +        else if (!child && flags & SCH_F_SET_NULL && g_strcmp0 (name, "*") == 0)
I think we would normally have () around a & expression.

2024-03-11 03:38 UTC, tony-vanderpeet approved these changes

2024-03-12 21:26 UTC, carlgsmith requested changes

2024-03-12 21:26 UTC, carlgsmith commented on schema.c
> +        else if (!child && (flags & SCH_F_SET_NULL) && g_strcmp0 (name, "*") == 0)
This should be in the sch_is_leaf_list section below.
Also please use the fn's for detecting leaf-lists rather than comp name and casting to xmlNode

2024-04-05 02:23 UTC, closed without merging

2024-04-05 02:23 UTC, gcampbell512 commented
This is a corner case caused by a call from restconf. The restconf code itself has been fixed.